apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{values.resource_id}}
  description: a Fedora VM
  links:
    - url: https://console-openshift-console.apps.crc.testing/k8s/ns/${{values.application_id}}-dev/kubevirt.io~v1~VirtualMachine/${{values.resource_id}}/console/standalone
      title: VM Console
      icon: web  
spec:
  type: virtual-machine
  owner: ${{values.owner}}
  system: system:${{values.application_id}}